properties.fileName=src/main/resources/.log
properties.pattern=%style{[%d{HH:mm:ss}]}{black} %highlight{[%-5p]}{FATAL=bright_red, ERROR=red, WARN=yellow, INFO=green, DEBUG=cyan} %style{%c{1}}{magenta} - %m%n
debug=false

informationService.events.enabled=true
informationService.messageEvents.enabled=true
informationService.scheduled.enabled=true
log4j2.plugins=Configuration

package.ClientSession.level=WARN
package.Decoder.level=WARN
package.File.level=WARN
package.Handshake.level=WARN
package.Tracker.level=WARN


